# Generated by Django 2.2.9 on 2020-02-22 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [("cards", "0104_remove_card_generic_mana_count")]

    operations = [
        migrations.CreateModel(
            name="CardSymbolCount",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=5)),
                ("count", models.IntegerField()),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="symbol_counts",
                        to="cards.Card",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CardSearchMetadata",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rules_without_reminders",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "card",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_metadata",
                        to="cards.Card",
                    ),
                ),
            ],
        ),
    ]
