# Generated by Django 3.1.3 on 2021-02-22 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardFaceSearchMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rules_without_reminders', models.CharField(blank=True, max_length=1000, null=True)),
                ('symbol_count_w', models.IntegerField(default=0)),
                ('symbol_count_u', models.IntegerField(default=0)),
                ('symbol_count_b', models.IntegerField(default=0)),
                ('symbol_count_r', models.IntegerField(default=0)),
                ('symbol_count_g', models.IntegerField(default=0)),
                ('symbol_count_c', models.IntegerField(default=0)),
                ('symbol_count_x', models.IntegerField(default=0)),
                ('symbol_count_w_u', models.IntegerField(default=0)),
                ('symbol_count_u_b', models.IntegerField(default=0)),
                ('symbol_count_b_r', models.IntegerField(default=0)),
                ('symbol_count_r_g', models.IntegerField(default=0)),
                ('symbol_count_g_w', models.IntegerField(default=0)),
                ('symbol_count_w_b', models.IntegerField(default=0)),
                ('symbol_count_u_r', models.IntegerField(default=0)),
                ('symbol_count_b_g', models.IntegerField(default=0)),
                ('symbol_count_r_w', models.IntegerField(default=0)),
                ('symbol_count_g_u', models.IntegerField(default=0)),
                ('symbol_count_2_w', models.IntegerField(default=0)),
                ('symbol_count_2_u', models.IntegerField(default=0)),
                ('symbol_count_2_b', models.IntegerField(default=0)),
                ('symbol_count_2_r', models.IntegerField(default=0)),
                ('symbol_count_2_g', models.IntegerField(default=0)),
                ('symbol_count_w_p', models.IntegerField(default=0)),
                ('symbol_count_u_p', models.IntegerField(default=0)),
                ('symbol_count_b_p', models.IntegerField(default=0)),
                ('symbol_count_r_p', models.IntegerField(default=0)),
                ('symbol_count_g_p', models.IntegerField(default=0)),
                ('symbol_count_generic', models.IntegerField(default=0)),
                ('produces_w', models.BooleanField(default=False)),
                ('produces_u', models.BooleanField(default=False)),
                ('produces_b', models.BooleanField(default=False)),
                ('produces_r', models.BooleanField(default=False)),
                ('produces_g', models.BooleanField(default=False)),
                ('produces_c', models.BooleanField(default=False)),
                ('card_face', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='search_metadata', to='cards.cardface')),
            ],
        ),
    ]
