# Generated by Django 4.2.16 on 2025-03-22 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0007_cardprice_cheapest_card"),
        ("cardsearch", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CardSearchMetadata",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_commander", models.BooleanField(default=False)),
                (
                    "card",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_metadata",
                        to="cards.card",
                    ),
                ),
            ],
        ),
    ]
