# Generated by Django 3.1.3 on 2020-12-31 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0018_auto_20201230_1807'),
        ('cardsearch', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CardSearchMetadata',
            new_name='CardFaceSearchMetadata',
        ),
        migrations.RemoveField(
            model_name='cardfacesearchmetadata',
            name='card',
        ),
        migrations.AddField(
            model_name='cardfacesearchmetadata',
            name='card_face',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='search_metadata', to='cards.cardface'),
            preserve_default=False,
        ),
    ]
