# Generated by Django 5.2.5 on 2025-09-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardsearch", "0002_cardsearchmetadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardsearchmetadata",
            name="super_sort_key",
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
