# Generated by Django 5.2.9 on 2026-06-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardsearch", "0003_cardsearchmetadata_super_sort_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardsearchmetadata",
            name="is_universes_beyond",
            field=models.BooleanField(default=False),
        ),
    ]
