# Generated by Django 2.2.9 on 2020-02-22 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cardsearch", "0003_cardsearchmetadata_symbol_count_generic")]

    operations = [
        migrations.AddField(
            model_name="cardsearchmetadata",
            name="symbol_count_x",
            field=models.IntegerField(default=0),
        )
    ]
