# Generated by Django 2.2.9 on 2020-02-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cardsearch", "0004_cardsearchmetadata_symbol_count_x")]

    operations = [
        migrations.AddField(
            model_name="cardsearchmetadata",
            name="produces_b",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cardsearchmetadata",
            name="produces_c",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cardsearchmetadata",
            name="produces_g",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cardsearchmetadata",
            name="produces_r",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cardsearchmetadata",
            name="produces_u",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cardsearchmetadata",
            name="produces_w",
            field=models.BooleanField(default=False),
        ),
    ]
