# Generated by Django 2.2.13 on 2020-12-22 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cardsearch", "0005_add_search_metadata_produces")]

    operations = [
        migrations.AddField(
            model_name="cardsearchmetadata",
            name="symbol_count_s",
            field=models.IntegerField(default=0),
        )
    ]
