# Generated by Django 3.1.3 on 2020-11-28 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scryfall_oracle_id', models.CharField(max_length=36)),
                ('name', models.CharField(max_length=200)),
                ('field_data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='CreateCardFace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scryfall_oracle_id', models.CharField(max_length=36)),
                ('name', models.CharField(max_length=200)),
                ('face_name', models.CharField(max_length=200)),
                ('side', models.CharField(blank=True, max_length=1, null=True)),
                ('field_data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='CreateCardFacePrinting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_scryfall_oracle_id', models.CharField(max_length=36)),
                ('card_name', models.CharField(max_length=200)),
                ('printing_uuid', models.CharField(max_length=36)),
                ('card_face_name', models.CharField(max_length=200)),
                ('side', models.CharField(blank=True, max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreateCardPrinting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_scryfall_oracle_id', models.CharField(max_length=36)),
                ('name', models.CharField(max_length=200)),
                ('uuid', models.CharField(max_length=36)),
                ('field_data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='DeleteCardFace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scryfall_oracle_id', models.CharField(max_length=36)),
                ('name', models.CharField(max_length=200)),
                ('face_name', models.CharField(max_length=200)),
                ('side', models.CharField(blank=True, max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeleteCardPrinting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_scryfall_oracle_id', models.CharField(max_length=36)),
                ('card_name', models.CharField(max_length=200)),
                ('uuid', models.CharField(max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='DestroyCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scryfall_oracle_id', models.CharField(max_length=36)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UpdateCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scryfall_oracle_id', models.CharField(max_length=36)),
                ('name', models.CharField(max_length=200)),
                ('field_data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='UpdateCardFace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scryfall_oracle_id', models.CharField(max_length=36)),
                ('name', models.CharField(max_length=200)),
                ('face_name', models.CharField(max_length=200)),
                ('side', models.CharField(blank=True, max_length=1, null=True)),
                ('field_data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='UpdateCardPrinting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_scryfall_oracle_id', models.CharField(max_length=36)),
                ('card_name', models.CharField(max_length=200)),
                ('uuid', models.CharField(max_length=36)),
                ('field_data', models.JSONField()),
            ],
        ),
    ]
