# Generated by Django 3.1.3 on 2020-12-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0003_auto_20201205_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateCardRuling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_mode', models.CharField(choices=[('UPDATE', 'Update'), ('CREATE', 'Create'), ('DELETE', 'Delete')], max_length=10)),
                ('card_name', models.CharField(max_length=100)),
                ('scryfall_oracle_id', models.CharField(max_length=36)),
                ('ruling_date', models.DateField()),
                ('ruling_text', models.CharField(max_length=4000)),
            ],
            options={
                'unique_together': {('scryfall_oracle_id', 'ruling_text')},
            },
        ),
    ]
