# Generated by Django 3.1.3 on 2020-12-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0006_auto_20201219_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatecardfaceprinting',
            name='field_data',
            field=models.JSONField(default='{}'),
            preserve_default=False,
        ),
    ]
