# Generated by Django 3.1.3 on 2020-12-20 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0007_updatecardfaceprinting_field_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='updatecardfaceprinting',
            old_name='card_scryfall_oracle_id',
            new_name='scryfall_id',
        ),
    ]
