# Generated by Django 3.1.3 on 2020-12-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0008_auto_20201220_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatecardfaceprinting',
            name='scryfall_oracle_id',
            field=models.CharField(default='', max_length=36),
            preserve_default=False,
        ),
    ]
