# Generated by Django 3.1.3 on 2020-12-29 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0009_updatecardfaceprinting_scryfall_oracle_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateCardFaceLocalisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_mode', models.CharField(choices=[('UPDATE', 'Update'), ('CREATE', 'Create'), ('DELETE', 'Delete')], max_length=10)),
                ('language_code', models.CharField(max_length=100)),
                ('printing_scryfall_id', models.CharField(max_length=36)),
                ('face_name', models.CharField(max_length=200)),
                ('side', models.CharField(blank=True, max_length=1, null=True)),
                ('field_data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='UpdateCardLocalisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_mode', models.CharField(choices=[('UPDATE', 'Update'), ('CREATE', 'Create'), ('DELETE', 'Delete')], max_length=10)),
                ('language_code', models.CharField(max_length=100)),
                ('printing_scryfall_id', models.CharField(max_length=36)),
                ('card_name', models.CharField(max_length=200)),
                ('field_data', models.JSONField()),
            ],
        ),
    ]
