# Generated by Django 3.1.3 on 2020-12-29 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0010_updatecardfacelocalisation_updatecardlocalisation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='updatecardlocalisation',
            unique_together={('language_code', 'printing_scryfall_id')},
        ),
    ]
