# Generated by Django 3.1.3 on 2020-12-29 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0011_auto_20201229_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updatecardfacelocalisation',
            name='side',
        ),
        migrations.AddField(
            model_name='updatecardfacelocalisation',
            name='face_printing_uuid',
            field=models.CharField(default='', max_length=36),
            preserve_default=False,
        ),
    ]
