# Generated by Django 3.1.3 on 2020-11-28 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardface',
            name='colour_sort_key',
        ),
        migrations.AddField(
            model_name='card',
            name='colour_sort_key',
            field=models.IntegerField(default=9),
            preserve_default=False,
        ),
    ]
