# Generated by Django 3.1.3 on 2021-04-23 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("cards", "0001_initial")]

    operations = [
        migrations.RemoveField(model_name="cardimage", name="downloaded"),
        migrations.RemoveField(model_name="cardimage", name="printed_language"),
        migrations.AddField(
            model_name="cardfacelocalisation",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cards.cardimage",
            ),
        ),
        migrations.AddField(
            model_name="cardimage",
            name="file_path",
            field=models.FilePathField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cardimage",
            name="scryfall_image_url",
            field=models.URLField(default="https://c1.scryfall.com/"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cardfaceprinting",
            name="frame_effects",
            field=models.ManyToManyField(
                blank=True, related_name="face_printings", to="cards.FrameEffect"
            ),
        ),
    ]
