# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-20 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cards", "0002_set_border_color")]

    operations = [
        migrations.AddField(
            model_name="cardprinting",
            name="json_id",
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        )
    ]
