# Generated by Django 3.1.3 on 2021-04-23 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cards", "0003_move_scryfall_illustration_id")]

    operations = [
        migrations.AlterField(
            model_name="cardimage",
            name="file_path",
            field=models.FilePathField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="cardimage",
            name="scryfall_image_url",
            field=models.URLField(unique=True),
        ),
    ]
