# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-21 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cards", "0003_cardprinting_json_id")]

    operations = [
        migrations.AddField(
            model_name="card",
            name="layout",
            field=models.CharField(
                choices=[
                    ("normal", "Normal"),
                    ("split", "Split"),
                    ("flip", "Flip"),
                    ("double-faced", "Double-faced"),
                    ("token", "Token"),
                    ("plane", "Plane"),
                    ("scheme", "Scheme"),
                    ("phenomenon", "Phenomenon"),
                    ("leveler", "Leveler"),
                    ("vanguard", "Vanguard"),
                    ("meld", "Meld"),
                ],
                default="normal",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="physicalcard",
            name="layout",
            field=models.CharField(
                choices=[
                    ("normal", "Normal"),
                    ("split", "Split"),
                    ("flip", "Flip"),
                    ("double-faced", "Double-faced"),
                    ("token", "Token"),
                    ("plane", "Plane"),
                    ("scheme", "Scheme"),
                    ("phenomenon", "Phenomenon"),
                    ("leveler", "Leveler"),
                    ("vanguard", "Vanguard"),
                    ("meld", "Meld"),
                ],
                max_length=50,
            ),
        ),
    ]
