# Generated by Django 3.2.9 on 2022-02-08 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_make_card_images_unique'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardfacelocalisation',
            options={'ordering': ('card_printing_face__card_face__side',)},
        ),
        migrations.AlterModelOptions(
            name='cardfaceprinting',
            options={'ordering': ('card_face__side',)},
        ),
        migrations.AlterModelOptions(
            name='cardprinting',
            options={'ordering': ['set__release_date', 'set__name', 'numerical_number']},
        ),
        migrations.AlterModelOptions(
            name='deckcard',
            options={'ordering': ['card__mana_value', 'card__name']},
        ),
        migrations.RenameField(
            model_name='card',
            old_name='converted_mana_cost',
            new_name='mana_value',
        ),
        migrations.RenameField(
            model_name='cardface',
            old_name='converted_mana_cost',
            new_name='mana_value',
        ),
    ]
