# Generated by Django 3.1.3 on 2020-12-06 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_auto_20201206_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardSubtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CardSupertype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CardType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='cardfacesupertype',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='cardfacesupertype',
            name='card_face',
        ),
        migrations.AlterUniqueTogether(
            name='cardfacetype',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='cardfacetype',
            name='card_face',
        ),
        migrations.DeleteModel(
            name='CardFaceSubtype',
        ),
        migrations.DeleteModel(
            name='CardFaceSupertype',
        ),
        migrations.DeleteModel(
            name='CardFaceType',
        ),
        migrations.AddField(
            model_name='cardface',
            name='subtypes',
            field=models.ManyToManyField(related_name='card_faces', to='cards.CardSubtype'),
        ),
        migrations.AddField(
            model_name='cardface',
            name='supertypes',
            field=models.ManyToManyField(related_name='card_faces', to='cards.CardSupertype'),
        ),
        migrations.AddField(
            model_name='cardface',
            name='types',
            field=models.ManyToManyField(related_name='card_faces', to='cards.CardType'),
        ),
    ]
