# Generated by Django 4.2.13 on 2024-06-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cards", "0005_rename_cmc_to_mana_value"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deckcard",
            options={"ordering": ["card__name"]},
        ),
        migrations.AlterField(
            model_name="cardface",
            name="rules_text",
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name="cardfacelocalisation",
            name="text",
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.DeleteModel(
            name="CardTag",
        ),
    ]
