# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-21 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_auto_20171221_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardlegality',
            name='restriction',
            field=models.CharField(choices=[('Legal', 'Legal'), ('Banned', 'Banned'), ('Restricted', 'Restricted')], default='Legal', max_length=50),
            preserve_default=False,
        ),
    ]
