# Generated by Django 3.1.3 on 2020-12-07 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_auto_20201206_2021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardface',
            old_name='cost',
            new_name='mana_cost',
        ),
    ]
