# Generated by Django 3.1.3 on 2020-12-07 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_auto_20201207_2357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardface',
            old_name='type_string',
            new_name='type_line',
        ),
    ]
