# Generated by Django 5.2.9 on 2026-05-17 11:42

import sylvan_library.bitfield.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0007_cardprice_cheapest_card"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardprinting",
            name="original_release_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="card",
            name="colour_identity",
            field=sylvan_library.bitfield.models.BitField(
                (
                    ("w", "White"),
                    ("u", "Blue"),
                    ("b", "Black"),
                    ("r", "Red"),
                    ("g", "Green"),
                ),
                default=None,
            ),
        ),
        migrations.AlterField(
            model_name="cardface",
            name="colour",
            field=sylvan_library.bitfield.models.BitField(
                (
                    ("w", "White"),
                    ("u", "Blue"),
                    ("b", "Black"),
                    ("r", "Red"),
                    ("g", "Green"),
                ),
                default=None,
            ),
        ),
        migrations.AlterField(
            model_name="cardface",
            name="colour_indicator",
            field=sylvan_library.bitfield.models.BitField(
                (
                    ("w", "White"),
                    ("u", "Blue"),
                    ("b", "Black"),
                    ("r", "Red"),
                    ("g", "Green"),
                ),
                default=None,
            ),
        ),
    ]
