# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-22 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cards", "0007_auto_20171222_1230")]

    operations = [
        migrations.AddField(
            model_name="card",
            name="original_text",
            field=models.CharField(blank=True, max_length=1000, null=True),
        )
    ]
