# Generated by Django 3.1.3 on 2020-12-07 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_auto_20201207_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardface',
            name='colour_sort_key',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
