# Generated by Django 3.1.3 on 2020-12-08 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_cardface_colour_sort_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardface',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
