# Generated by Django 5.2.9 on 2026-06-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0008_cardprinting_original_release_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardprinting",
            name="is_universes_beyond",
            field=models.BooleanField(default=False),
        ),
    ]
