# Generated by Django 3.1.3 on 2020-12-16 23:36

import bitfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_auto_20201208_2042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardface',
            options={'ordering': ('side',)},
        ),
        migrations.AlterField(
            model_name='card',
            name='colour_identity',
            field=bitfield.models.BitField((('w', 'White'), ('u', 'Blue'), ('b', 'Black'), ('r', 'Red'), ('g', 'Green')), default=None),
        ),
        migrations.AlterField(
            model_name='cardface',
            name='colour',
            field=bitfield.models.BitField((('w', 'White'), ('u', 'Blue'), ('b', 'Black'), ('r', 'Red'), ('g', 'Green')), default=None),
        ),
        migrations.AlterField(
            model_name='cardface',
            name='colour_indicator',
            field=bitfield.models.BitField((('w', 'White'), ('u', 'Blue'), ('b', 'Black'), ('r', 'Red'), ('g', 'Green')), default=None),
        ),
    ]
