# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-22 05:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("cards", "0009_card_original_type")]

    operations = [
        migrations.RemoveField(model_name="card", name="original_text"),
        migrations.RemoveField(model_name="card", name="original_type"),
    ]
