# Generated by Django 3.1.3 on 2020-12-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_auto_20201216_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardface',
            name='subtypes',
            field=models.ManyToManyField(blank=True, related_name='card_faces', to='cards.CardSubtype'),
        ),
        migrations.AlterField(
            model_name='cardface',
            name='supertypes',
            field=models.ManyToManyField(blank=True, related_name='card_faces', to='cards.CardSupertype'),
        ),
    ]
