# Generated by Django 3.1.3 on 2020-12-19 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0011_auto_20201219_1739'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardlegality',
            options={'verbose_name_plural': 'card legalities'},
        ),
    ]
