# Generated by Django 3.1.3 on 2020-12-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0012_auto_20201219_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardprinting',
            name='number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cardprinting',
            name='numerical_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
