# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-22 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cards", "0012_cardprinting_watermark")]

    operations = [
        migrations.AddField(
            model_name="card",
            name="border_colour",
            field=models.CharField(blank=True, max_length=10, null=True),
        )
    ]
