# Generated by Django 3.1.3 on 2020-12-20 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0014_frameeffect'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardfaceprinting',
            name='frame_effects',
            field=models.ManyToManyField(related_name='face_printings', to='cards.FrameEffect'),
        ),
        migrations.AlterField(
            model_name='cardfaceprinting',
            name='card_face',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_printings', to='cards.cardface'),
        ),
        migrations.AlterField(
            model_name='cardfaceprinting',
            name='card_printing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_printings', to='cards.cardprinting'),
        ),
    ]
