# Generated by Django 3.1.3 on 2020-12-29 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0015_auto_20201220_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userownedcard',
            old_name='printing_language',
            new_name='card_localisation',
        ),
        migrations.AlterUniqueTogether(
            name='userownedcard',
            unique_together={('card_localisation', 'owner')},
        ),
        migrations.RenameModel(
            old_name='CardPrintingLanguage',
            new_name='CardLocalisation',
        ),
        migrations.CreateModel(
            name='CardFaceLocalisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_name', models.CharField(max_length=200)),
                ('flavour_text', models.CharField(blank=True, max_length=500, null=True)),
                ('type', models.CharField(blank=True, max_length=200, null=True)),
                ('multiverse_id', models.IntegerField(blank=True, null=True)),
                ('text', models.CharField(blank=True, max_length=1000, null=True)),
                ('card_printing_face', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localised_faces', to='cards.cardfaceprinting')),
                ('localisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localised_faces', to='cards.cardlocalisation')),
            ],
            options={
                'unique_together': {('card_printing_face', 'localisation')},
            },
        ),
    ]
