# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-22 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0015_auto_20171222_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='is_reserved',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
