# Generated by Django 3.1.3 on 2020-12-29 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0016_auto_20201229_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardfacelocalisation',
            name='multiverse_id',
        ),
        migrations.AlterField(
            model_name='cardlocalisation',
            name='card_printing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localisations', to='cards.cardprinting'),
        ),
        migrations.AlterUniqueTogether(
            name='cardlocalisation',
            unique_together={('language', 'card_printing')},
        ),
        migrations.RemoveField(
            model_name='cardlocalisation',
            name='flavour_text',
        ),
        migrations.RemoveField(
            model_name='cardlocalisation',
            name='text',
        ),
        migrations.RemoveField(
            model_name='cardlocalisation',
            name='type',
        ),
    ]
