# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-30 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0016_card_is_reserved'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardprinting',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
