# Generated by Django 3.1.3 on 2020-12-30 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0017_auto_20201229_2111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercardchange',
            old_name='printing_language',
            new_name='card_localisation',
        ),
        migrations.AlterField(
            model_name='cardfaceprinting',
            name='card_face',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_printings', to='cards.cardface'),
        ),
    ]
