# Generated by Django 3.1.3 on 2021-01-10 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0018_auto_20201230_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardprice',
            name='currency',
            field=models.CharField(default='USD', max_length=5),
        ),
        migrations.AddField(
            model_name='cardprice',
            name='foil',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cardprice',
            name='stock_type',
            field=models.CharField(choices=[('paper', 'Paper'), ('mtgo', 'MTGO')], default='paper', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardprice',
            name='store',
            field=models.CharField(default='cardkingdom', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardprice',
            name='trade_direction',
            field=models.CharField(choices=[('buy', 'buy'), ('sell', 'Sell')], default='buy', max_length=5),
        ),
        migrations.AlterField(
            model_name='cardprice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterUniqueTogether(
            name='cardprice',
            unique_together={('date', 'printing', 'stock_type', 'foil', 'store', 'trade_direction')},
        ),
        migrations.RemoveField(
            model_name='cardprice',
            name='price_type',
        ),
    ]
