# Generated by Django 3.1.3 on 2021-01-10 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0019_auto_20210110_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardprice',
            name='retail_type',
            field=models.CharField(choices=[('retail', 'Retail'), ('buylist', 'Buylist')], default='buy', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='cardprice',
            unique_together={('date', 'printing', 'stock_type', 'foil', 'store', 'retail_type')},
        ),
        migrations.RemoveField(
            model_name='cardprice',
            name='trade_direction',
        ),
    ]
