# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-08 07:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("cards", "0020_auto_20180206_2310")]

    operations = [
        migrations.RenameField(
            model_name="card", old_name="colour_identity", new_name="colour_identities"
        ),
        migrations.RenameField(
            model_name="card", old_name="colour", new_name="colours"
        ),
        migrations.RemoveField(model_name="card", name="colour_count"),
    ]
