# Generated by Django 3.1.3 on 2021-01-12 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0020_auto_20210110_2342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardprice',
            old_name='printing',
            new_name='card_printing',
        ),
        migrations.RenameField(
            model_name='cardprice',
            old_name='price',
            new_name='value',
        ),
        migrations.AlterUniqueTogether(
            name='cardprice',
            unique_together={('date', 'card_printing', 'stock_type', 'foil')},
        ),
        migrations.RemoveField(
            model_name='cardprice',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='cardprice',
            name='retail_type',
        ),
        migrations.RemoveField(
            model_name='cardprice',
            name='store',
        ),
    ]
