# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-18 05:54
from __future__ import unicode_literals

import bitfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("cards", "0022_card_colour_count")]

    operations = [
        migrations.AddField(
            model_name="card",
            name="colour_flags",
            field=bitfield.models.BitField(
                ("white", "blue", "black", "red", "green"), default=0
            ),
        ),
        migrations.AddField(
            model_name="card",
            name="colour_identity_flags",
            field=bitfield.models.BitField(
                ("white", "blue", "black", "red", "green"), default=0
            ),
        ),
    ]
