# Generated by Django 3.1.3 on 2021-01-15 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0022_cardprinting_lowest_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardprinting',
            name='lowest_price',
        ),
        migrations.AddField(
            model_name='cardprinting',
            name='most_recent_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recent_price_printing', to='cards.cardprice'),
        ),
    ]
