# Generated by Django 3.1.3 on 2021-01-27 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0023_auto_20210115_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardprinting',
            name='most_recent_price',
        ),
        migrations.AddField(
            model_name='cardprice',
            name='is_latest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cardprice',
            name='mtgo_foil_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cardprice',
            name='mtgo_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cardprice',
            name='paper_foil_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cardprice',
            name='paper_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='cardprice',
            unique_together={('date', 'card_printing')},
        ),
        migrations.RemoveField(
            model_name='cardprice',
            name='foil',
        ),
        migrations.RemoveField(
            model_name='cardprice',
            name='stock_type',
        ),
        migrations.RemoveField(
            model_name='cardprice',
            name='value',
        ),
    ]
