# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-21 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cards", "0024_auto_20180218_1907")]

    operations = [
        migrations.AddField(
            model_name="card",
            name="colour_sort_key",
            field=models.IntegerField(default=0),
            preserve_default=False,
        )
    ]
