# Generated by Django 3.1.3 on 2021-02-17 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0024_auto_20210127_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardprice',
            name='is_latest',
        ),
        migrations.AddField(
            model_name='cardprinting',
            name='latest_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='latest_printing', to='cards.cardprice'),
        ),
    ]
