# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-21 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0025_card_colour_sort_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='colour_weight',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
