# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-24 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0026_card_colour_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='colour',
            name='bit_value',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
