# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-25 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cards", "0027_colour_bit_value")]

    operations = [
        migrations.AlterField(
            model_name="cardprinting",
            name="json_id",
            field=models.CharField(max_length=40, unique=True),
        )
    ]
