# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-06 08:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("cards", "0029_auto_20180703_2320")]

    operations = [migrations.RemoveField(model_name="cardprinting", name="mci_number")]
