# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-06 08:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0030_remove_cardprinting_mci_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='hand_modifier',
        ),
        migrations.RemoveField(
            model_name='card',
            name='life_modifier',
        ),
    ]
