# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-06 08:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0031_auto_20181106_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='border_colour',
        ),
    ]
