# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-06 08:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("cards", "0032_remove_set_border_colour")]

    operations = [
        migrations.RemoveField(model_name="language", name="mci_code"),
        migrations.RemoveField(model_name="set", name="mci_code"),
    ]
