# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-06 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0034_auto_20181106_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
