# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-04 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cards", "0035_auto_20181106_2216")]

    operations = [
        migrations.AlterField(
            model_name="rarity",
            name="symbol",
            field=models.CharField(max_length=5, unique=True),
        )
    ]
