# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-04 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cards", "0036_auto_20190104_2226")]

    operations = [
        migrations.AlterField(
            model_name="rarity",
            name="name",
            field=models.CharField(max_length=30, unique=True),
        )
    ]
