# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-05 01:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("cards", "0038_auto_20190105_1054")]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="layout",
            field=models.CharField(
                choices=[
                    ("normal", "Normal"),
                    ("split", "Split"),
                    ("flip", "Flip"),
                    ("transform", "Transform"),
                    ("token", "Token"),
                    ("planar", "Planar"),
                    ("scheme", "Scheme"),
                    ("phenomenon", "Phenomenon"),
                    ("leveler", "Leveler"),
                    ("vanguard", "Vanguard"),
                    ("meld", "Meld"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="physicalcard",
            name="layout",
            field=models.CharField(
                choices=[
                    ("normal", "Normal"),
                    ("split", "Split"),
                    ("flip", "Flip"),
                    ("transform", "Transform"),
                    ("token", "Token"),
                    ("planar", "Planar"),
                    ("scheme", "Scheme"),
                    ("phenomenon", "Phenomenon"),
                    ("leveler", "Leveler"),
                    ("vanguard", "Vanguard"),
                    ("meld", "Meld"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="set",
            name="block",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sets",
                to="cards.Block",
            ),
        ),
    ]
