# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-05 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cards", "0043_auto_20190105_1602")]

    operations = [
        migrations.AddField(
            model_name="cardprintinglanguage",
            name="flavour_text",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="cardprintinglanguage",
            name="type",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
