# Generated by Django 2.1.5 on 2019-02-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0044_auto_20190105_1805'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardprinting',
            options={'ordering': ['set__release_date']},
        ),
        migrations.AddField(
            model_name='cardprintinglanguage',
            name='scryfall_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
