# Generated by Django 2.1.5 on 2019-02-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cards", "0047_auto_20190210_1401")]

    operations = [
        migrations.RemoveField(model_name="cardprintinglanguage", name="scryfall_id"),
        migrations.AddField(
            model_name="cardprinting",
            name="scryfall_id",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
