# Generated by Django 2.1.7 on 2019-02-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0049_cardimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='side',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
