# Generated by Django 2.1.7 on 2019-02-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cards", "0053_cardprinting_is_timeshifted")]

    operations = [
        migrations.AddField(
            model_name="format",
            name="code",
            field=models.CharField(default="default", max_length=100),
            preserve_default=False,
        )
    ]
