# Generated by Django 2.1.7 on 2019-02-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0054_format_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='format',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
