# Generated by Django 2.1.7 on 2019-03-23 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("cards", "0055_auto_20190223_1653")]

    operations = [
        migrations.RemoveField(model_name="cardprinting", name="release_date")
    ]
