# Generated by Django 2.1.7 on 2019-03-17 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0055_auto_20190223_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardprinting',
            old_name='json_id',
            new_name='old_json_id',
        ),
    ]
