# Generated by Django 2.1.7 on 2019-04-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('cards', '0057_auto_20190406_1722'), ('cards', '0058_auto_20190406_1739'), ('cards', '0059_auto_20190406_1739'), ('cards', '0060_auto_20190406_1927'), ('cards', '0061_auto_20190406_1934'), ('cards', '0062_cardprinting_is_token'), ('cards', '0063_auto_20190406_2007'), ('cards', '0064_auto_20190406_2027'), ('cards', '0065_auto_20190406_2141')]

    dependencies = [
        ('cards', '0056_remove_cardprinting_release_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardprinting',
            options={'ordering': ['set__release_date', 'number']},
        ),
        migrations.AddField(
            model_name='card',
            name='scryfall_oracle_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cardprinting',
            name='artist',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='is_token',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='layout',
            field=models.CharField(choices=[('normal', 'Normal'), ('split', 'Split'), ('flip', 'Flip'), ('transform', 'Transform'), ('token', 'Token'), ('planar', 'Planar'), ('scheme', 'Scheme'), ('leveler', 'Leveler'), ('vanguard', 'Vanguard'), ('meld', 'Meld'), ('host', 'Host'), ('augment', 'Augment'), ('saga', 'Saga'), {'double_faced_token', 'Double-faced Token'}], max_length=50),
        ),
        migrations.AlterField(
            model_name='physicalcard',
            name='layout',
            field=models.CharField(choices=[('normal', 'Normal'), ('split', 'Split'), ('flip', 'Flip'), ('transform', 'Transform'), ('token', 'Token'), ('planar', 'Planar'), ('scheme', 'Scheme'), ('leveler', 'Leveler'), ('vanguard', 'Vanguard'), ('meld', 'Meld'), ('host', 'Host'), ('augment', 'Augment'), ('saga', 'Saga'), {'double_faced_token', 'Double-faced Token'}], max_length=50),
        ),
        migrations.AlterField(
            model_name='card',
            name='layout',
            field=models.CharField(choices=[('normal', 'Normal'), ('split', 'Split'), ('flip', 'Flip'), ('transform', 'Transform'), ('token', 'Token'), ('planar', 'Planar'), ('scheme', 'Scheme'), ('leveler', 'Leveler'), ('vanguard', 'Vanguard'), ('meld', 'Meld'), ('host', 'Host'), ('augment', 'Augment'), ('saga', 'Saga'), ('double_faced_token', 'Double-faced Token')], max_length=50),
        ),
        migrations.AlterField(
            model_name='physicalcard',
            name='layout',
            field=models.CharField(choices=[('normal', 'Normal'), ('split', 'Split'), ('flip', 'Flip'), ('transform', 'Transform'), ('token', 'Token'), ('planar', 'Planar'), ('scheme', 'Scheme'), ('leveler', 'Leveler'), ('vanguard', 'Vanguard'), ('meld', 'Meld'), ('host', 'Host'), ('augment', 'Augment'), ('saga', 'Saga'), ('double_faced_token', 'Double-faced Token')], max_length=50),
        ),
    ]
