# Generated by Django 2.1.7 on 2019-03-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0056_auto_20190317_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardprinting',
            name='json_id',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
