# Generated by Django 2.1.7 on 2019-03-17 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0057_cardprinting_json_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardprinting',
            name='old_json_id',
        ),
        migrations.AlterField(
            model_name='cardprinting',
            name='json_id',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
