# Generated by Django 2.2 on 2019-05-01 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0062_auto_20190430_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
