# Generated by Django 2.2 on 2019-05-09 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0065_deck_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='deckcard',
            name='is_commander',
            field=models.BooleanField(default=False),
        ),
    ]
