# Generated by Django 2.2.1 on 2019-05-25 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cards", "0066_deckcard_is_commander")]

    operations = [
        migrations.AddField(
            model_name="colour",
            name="chart_colour",
            field=models.CharField(default="#ffffff", max_length=20),
            preserve_default=False,
        )
    ]
