# Generated by Django 2.2.1 on 2019-05-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cards", "0067_colour_chart_colour")]

    operations = [
        migrations.AddField(
            model_name="deck",
            name="exclude_colours",
            field=models.ManyToManyField(
                related_name="exclude_from_decks", to="cards.Colour"
            ),
        )
    ]
