# Generated by Django 2.2.1 on 2019-07-18 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cards", "0071_auto_20190622_1356")]

    operations = [
        migrations.AddField(
            model_name="card",
            name="display_name",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        )
    ]
