# Generated by Django 2.2.1 on 2019-07-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cards", "0072_card_display_name")]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        )
    ]
