# Generated by Django 2.2.1 on 2019-07-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cards", "0073_auto_20190719_1840")]

    operations = [
        migrations.AddField(
            model_name="deck",
            name="is_private",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="deck",
            name="is_prototype",
            field=models.BooleanField(default=False),
        ),
    ]
