# Generated by Django 2.2.1 on 2019-08-08 19:57

import bitfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("cards", "0074_auto_20190728_1310")]

    operations = [
        migrations.AddField(
            model_name="card",
            name="colour_indicator_flags",
            field=bitfield.models.BitField(
                ("white", "blue", "black", "red", "green"), default=0
            ),
        )
    ]
