# Generated by Django 2.2.1 on 2019-08-08 22:10

import bitfield.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cards", "0075_card_colour_indicator_flags")]

    operations = [
        migrations.AddField(
            model_name="cardprinting",
            name="duel_deck_side",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name="card",
            name="colour_indicator_flags",
            field=bitfield.models.BitField(
                ("white", "blue", "black", "red", "green"), default=None
            ),
        ),
    ]
