# Generated by Django 2.2.1 on 2019-08-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cards", "0076_auto_20190808_2210")]

    operations = [
        migrations.AddField(
            model_name="card",
            name="face_cmc",
            field=models.FloatField(blank=True, null=True),
        )
    ]
