# Generated by Django 2.2.1 on 2019-08-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cards", "0079_cardprinting_frame_effect")]

    operations = [
        migrations.AddField(
            model_name="cardprinting",
            name="frame_version",
            field=models.CharField(blank=True, max_length=50, null=True),
        )
    ]
