# Generated by Django 2.2.1 on 2019-08-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cards", "0080_cardprinting_frame_version")]

    operations = [
        migrations.AddField(
            model_name="card",
            name="hand_modifier",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="card",
            name="life_modifier",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="card",
            name="num_hand_modifier",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="card",
            name="num_life_modifier",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
