# Generated by Django 2.2.1 on 2019-08-24 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cards", "0081_card_hand_life_modifiers")]

    operations = [
        migrations.AddField(
            model_name="cardprinting",
            name="has_foil",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="cardprinting",
            name="has_non_foil",
            field=models.BooleanField(default=True),
        ),
    ]
