# Generated by Django 2.2.1 on 2019-08-25 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cards", "0082_add_card_printing_foil_non_foil")]

    operations = [
        migrations.AddField(
            model_name="cardprinting",
            name="is_alternative",
            field=models.BooleanField(default=False),
        )
    ]
