# Generated by Django 2.2.1 on 2019-08-25 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cards", "0084_auto_20190825_2252")]

    operations = [
        migrations.AddField(
            model_name="cardprinting",
            name="is_full_art",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cardprinting",
            name="is_oversized",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cardprinting",
            name="is_textless",
            field=models.BooleanField(default=False),
        ),
    ]
