# Generated by Django 2.2.1 on 2019-08-29 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cards", "0085_auto_20190825_2333")]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="is_reserved",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="card", name="is_token", field=models.BooleanField(default=False)
        ),
        migrations.AlterField(
            model_name="card",
            name="num_hand_modifier",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="card",
            name="num_life_modifier",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="card", name="num_loyalty", field=models.FloatField(default=0)
        ),
        migrations.AlterField(
            model_name="card", name="num_power", field=models.FloatField(default=0)
        ),
        migrations.AlterField(
            model_name="card", name="num_toughness", field=models.FloatField(default=0)
        ),
    ]
