# Generated by Django 2.2.1 on 2019-08-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cards", "0086_auto_20190829_1815")]

    operations = [
        migrations.AddField(
            model_name="cardprinting",
            name="is_paper",
            field=models.BooleanField(default=True),
        )
    ]
