# Generated by Django 2.2.1 on 2019-08-29 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cards", "0088_cardprinting_is_reprint")]

    operations = [
        migrations.AddField(
            model_name="cardprinting",
            name="is_promo",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cardprinting",
            name="is_story_spotlight",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cardprinting",
            name="magic_card_market_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cardprinting",
            name="magic_card_market_meta_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cardprinting",
            name="mtg_arena_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cardprinting",
            name="mtg_stocks_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cardprinting",
            name="mtgo_foil_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cardprinting",
            name="mtgo_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cardprinting",
            name="scryfall_illustration_id",
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name="cardprinting",
            name="tcg_player_product_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
