# Generated by Django 2.2.1 on 2019-08-31 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("cards", "0089_auto_20190829_2300")]

    operations = [
        migrations.CreateModel(
            name="CardPrice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.FloatField()),
                ("date", models.DateField()),
                (
                    "price_type",
                    models.CharField(
                        choices=[("paper", "Paper"), ("paper_foil", "Paper Foil")],
                        max_length=50,
                    ),
                ),
                (
                    "printing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="cards.CardPrinting",
                    ),
                ),
            ],
        )
    ]
