# Generated by Django 2.2.1 on 2019-09-02 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("cards", "0091_card_edh_rec_rank")]

    operations = [
        migrations.RenameField(
            model_name="set", old_name="card_count", new_name="total_set_size"
        ),
        migrations.AddField(
            model_name="set", name="base_set_size", field=models.IntegerField(default=0)
        ),
        migrations.AddField(
            model_name="set",
            name="is_foil_only",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="set",
            name="is_foreign_only",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="set",
            name="is_online_only",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="set",
            name="is_partial_preview",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="set",
            name="magic_card_market_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="set",
            name="magic_card_market_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="set",
            name="mtgo_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="set",
            name="parent_set",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_sets",
                to="cards.Set",
            ),
        ),
        migrations.AddField(
            model_name="set",
            name="tcg_player_group_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
