# Generated by Django 2.2.1 on 2019-10-03 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cards", "0092_auto_20190902_2236")]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="layout",
            field=models.CharField(
                choices=[
                    ("normal", "Normal"),
                    ("split", "Split"),
                    ("flip", "Flip"),
                    ("transform", "Transform"),
                    ("token", "Token"),
                    ("planar", "Planar"),
                    ("scheme", "Scheme"),
                    ("leveler", "Leveler"),
                    ("vanguard", "Vanguard"),
                    ("meld", "Meld"),
                    ("host", "Host"),
                    ("augment", "Augment"),
                    ("saga", "Saga"),
                    ("emblem", "Emblem"),
                    ("double_faced_token", "Double-faced Token"),
                    ("aftermath", "Aftermath"),
                    ("adventure", "Adventure"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="physicalcard",
            name="layout",
            field=models.CharField(
                choices=[
                    ("normal", "Normal"),
                    ("split", "Split"),
                    ("flip", "Flip"),
                    ("transform", "Transform"),
                    ("token", "Token"),
                    ("planar", "Planar"),
                    ("scheme", "Scheme"),
                    ("leveler", "Leveler"),
                    ("vanguard", "Vanguard"),
                    ("meld", "Meld"),
                    ("host", "Host"),
                    ("augment", "Augment"),
                    ("saga", "Saga"),
                    ("emblem", "Emblem"),
                    ("double_faced_token", "Double-faced Token"),
                    ("aftermath", "Aftermath"),
                    ("adventure", "Adventure"),
                ],
                max_length=50,
            ),
        ),
    ]
