# Generated by Django 2.2.1 on 2019-11-07 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cards", "0093_auto_20191003_2229")]

    operations = [
        migrations.AlterField(
            model_name="cardprice",
            name="price_type",
            field=models.CharField(
                choices=[
                    ("paper", "Paper"),
                    ("paper_foil", "Paper Foil"),
                    ("mtgo", "MTGO"),
                ],
                max_length=50,
            ),
        )
    ]
