# Generated by Django 2.2.1 on 2019-11-07 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cards", "0094_auto_20191107_2115")]

    operations = [
        migrations.AlterField(
            model_name="cardprice",
            name="price_type",
            field=models.CharField(
                choices=[
                    ("paper", "Paper"),
                    ("paper_foil", "Paper Foil"),
                    ("mtgo", "MTGO"),
                    ("mtgo_foil", "MTGO Foil"),
                ],
                max_length=50,
            ),
        )
    ]
