# Generated by Django 2.2.1 on 2019-11-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cards", "0097_auto_20191109_1206")]

    operations = [
        migrations.AlterField(
            model_name="cardprinting",
            name="frame_effect",
            field=models.CharField(
                blank=True,
                choices=[
                    ("colorshifted", "colorshifted"),
                    ("compasslanddfc", "compasslanddfc"),
                    ("devoid", "devoid"),
                    ("draft", "draft"),
                    ("extendedart", "extendedart"),
                    ("inverted", "inverted"),
                    ("legendary", "legendary"),
                    ("miracle", "miracle"),
                    ("mooneldrazidfc", "mooneldrazidfc"),
                    ("nyxtouched", "nyxtouched"),
                    ("originpwdfc", "originpwdfc"),
                    ("showcase", "showcase"),
                    ("sunmoondfc", "sunmoondfc"),
                    ("tombstone", "tombstone"),
                ],
                max_length=50,
                null=True,
            ),
        )
    ]
