# Generated by Django 2.2.1 on 2019-12-04 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cards", "0098_auto_20191109_1210")]

    operations = [
        migrations.AlterField(
            model_name="set", name="keyrune_code", field=models.CharField(max_length=50)
        )
    ]
