# Generated by Django 2.2.8 on 2019-12-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cards", "0099_auto_20191204_2217")]

    operations = [
        migrations.AddField(
            model_name="card",
            name="colour_indicator_count",
            field=models.IntegerField(default=0),
            preserve_default=False,
        )
    ]
