# Generated by Django 2.2.8 on 2019-12-26 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("cards", "0100_card_colour_indicator_count")]

    operations = [
        migrations.RenameField(
            model_name="card",
            old_name="colour_indicator_count",
            new_name="colour_identity_count",
        )
    ]
