# Generated by Django 2.2.8 on 2020-02-06 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cards", "0102_auto_20200117_2321")]

    operations = [
        migrations.AlterModelOptions(
            name="deckcard",
            options={"ordering": ["card__cmc", "card__colour_sort_key", "card__name"]},
        ),
        migrations.AddField(
            model_name="card",
            name="generic_mana_count",
            field=models.IntegerField(default=0),
        ),
    ]
