# Generated by Django 2.2.9 on 2020-02-22 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("cards", "0103_add_card_generic_mana_count")]

    operations = [migrations.RemoveField(model_name="card", name="generic_mana_count")]
