# Generated by Django 2.2.9 on 2020-02-28 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cards", "0104_remove_card_generic_mana_count")]

    operations = [
        migrations.AlterField(
            model_name="cardprice",
            name="price_type",
            field=models.CharField(
                choices=[
                    ("paper", "Paper"),
                    ("paperFoil", "Paper Foil"),
                    ("mtgo", "MTGO"),
                    ("mtgoFoil", "MTGO Foil"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cardprice", unique_together={("date", "printing", "price_type")}
        ),
    ]
