# Generated by Django 2.2.9 on 2020-05-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cards", "0106_add_companion_frame_effect")]

    operations = [
        migrations.AddField(
            model_name="cardprinting",
            name="numerical_number",
            field=models.IntegerField(blank=True, null=True),
        )
    ]
