# Generated by Django 2.2.13 on 2020-10-01 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cards", "0107_cardprinting_numerical_number")]

    operations = [
        migrations.AlterModelOptions(
            name="cardprinting",
            options={
                "ordering": [
                    "set__release_date",
                    "set__name",
                    "numerical_number",
                    "number",
                ]
            },
        ),
        migrations.AlterField(
            model_name="card",
            name="layout",
            field=models.CharField(
                choices=[
                    ("normal", "Normal"),
                    ("split", "Split"),
                    ("flip", "Flip"),
                    ("transform", "Transform"),
                    ("token", "Token"),
                    ("planar", "Planar"),
                    ("scheme", "Scheme"),
                    ("leveler", "Leveler"),
                    ("vanguard", "Vanguard"),
                    ("meld", "Meld"),
                    ("host", "Host"),
                    ("augment", "Augment"),
                    ("saga", "Saga"),
                    ("emblem", "Emblem"),
                    ("double_faced_token", "Double-faced Token"),
                    ("aftermath", "Aftermath"),
                    ("adventure", "Adventure"),
                    ("modal_dfc", "Modal DFC"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="physicalcard",
            name="layout",
            field=models.CharField(
                choices=[
                    ("normal", "Normal"),
                    ("split", "Split"),
                    ("flip", "Flip"),
                    ("transform", "Transform"),
                    ("token", "Token"),
                    ("planar", "Planar"),
                    ("scheme", "Scheme"),
                    ("leveler", "Leveler"),
                    ("vanguard", "Vanguard"),
                    ("meld", "Meld"),
                    ("host", "Host"),
                    ("augment", "Augment"),
                    ("saga", "Saga"),
                    ("emblem", "Emblem"),
                    ("double_faced_token", "Double-faced Token"),
                    ("aftermath", "Aftermath"),
                    ("adventure", "Adventure"),
                    ("modal_dfc", "Modal DFC"),
                ],
                max_length=50,
            ),
        ),
    ]
