# Generated by Django 2.2.13 on 2020-11-15 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cards", "0109_add_full_art_frame_effect")]

    operations = [
        migrations.AlterField(
            model_name="card", name="layout", field=models.CharField(max_length=50)
        ),
        migrations.AlterField(
            model_name="physicalcard",
            name="layout",
            field=models.CharField(max_length=50),
        ),
    ]
