# Generated by Django 2.2.13 on 2020-12-22 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cards", "0110_remove_card_layout_choices")]

    operations = [
        migrations.AlterField(
            model_name="cardprinting",
            name="frame_effect",
            field=models.CharField(blank=True, max_length=50, null=True),
        )
    ]
