# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 11:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('release_date', models.DateField()),
                ('name', models.CharField(max_length=200)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spellbook.Block')),
            ],
        ),
    ]
