# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 06:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spellbook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.CharField(blank=True, max_length=50)),
                ('cmc', models.IntegerField()),
                ('colour', models.IntegerField()),
                ('colour_identity', models.IntegerField()),
                ('colour_count', models.IntegerField()),
                ('type', models.CharField(blank=True, max_length=100)),
                ('subtype', models.CharField(blank=True, max_length=100)),
                ('power', models.CharField(blank=True, max_length=20)),
                ('num_power', models.IntegerField()),
                ('toughness', models.CharField(blank=True, max_length=20)),
                ('num_toughness', models.IntegerField()),
                ('loyalty', models.CharField(blank=True, max_length=20)),
                ('num_loyalty', models.IntegerField()),
                ('rules_text', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='CardLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=1)),
                ('cardFrom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardFrom', to='spellbook.Card')),
                ('cardTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardTo', to='spellbook.Card')),
            ],
        ),
        migrations.CreateModel(
            name='CardPrinting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rarity', models.CharField(max_length=1)),
                ('flavour_text', models.CharField(max_length=350)),
                ('artist', models.CharField(max_length=100)),
                ('collector_number', models.IntegerField(blank=True)),
                ('collector_letter', models.CharField(blank=True, max_length=1)),
                ('original_text', models.CharField(blank=True, max_length=1000)),
                ('original_type', models.CharField(blank=True, max_length=200)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spellbook.Card')),
            ],
        ),
        migrations.CreateModel(
            name='CardPrintingLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50)),
                ('card_name', models.CharField(max_length=200)),
                ('cardPrinting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spellbook.CardPrinting')),
            ],
        ),
        migrations.CreateModel(
            name='CardRuling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('text', models.CharField(max_length=1000)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spellbook.Card')),
            ],
        ),
        migrations.CreateModel(
            name='CardTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CardTagLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spellbook.Card')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spellbook.CardTag')),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField()),
                ('last_modiifed', models.DateField()),
                ('name', models.CharField(max_length=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeckCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spellbook.Card')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spellbook.Deck')),
            ],
        ),
        migrations.CreateModel(
            name='Subtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserCardChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difference', models.IntegerField()),
                ('cardPrintingLanguage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spellbook.CardPrintingLanguage')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserOwnedCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('cardPrintingLanguage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spellbook.CardPrintingLanguage')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='set',
            name='release_date',
            field=models.DateField(blank=True),
        ),
        migrations.AddField(
            model_name='cardprinting',
            name='set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spellbook.Set'),
        ),
    ]
