# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 06:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0002_auto_20160613_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardlink',
            old_name='cardFrom',
            new_name='card_from',
        ),
        migrations.RenameField(
            model_name='cardlink',
            old_name='cardTo',
            new_name='card_to',
        ),
        migrations.RenameField(
            model_name='cardprintinglanguage',
            old_name='cardPrinting',
            new_name='card_printing',
        ),
        migrations.RenameField(
            model_name='usercardchange',
            old_name='cardPrintingLanguage',
            new_name='card_printing_language',
        ),
        migrations.RenameField(
            model_name='userownedcard',
            old_name='cardPrintingLanguage',
            new_name='card_printing_language',
        ),
    ]
