# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0003_auto_20160613_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='code',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
