# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 13:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0004_auto_20160613_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spellbook.Block'),
        ),
    ]
