# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 09:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0009_auto_20160614_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='start_date',
            new_name='release_date',
        ),
    ]
