# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0010_auto_20160614_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='release_date',
            field=models.DateField(),
        ),
    ]
