# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0012_auto_20160618_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='num_loyalty',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='card',
            name='num_power',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='card',
            name='num_toughness',
            field=models.FloatField(),
        ),
    ]
