# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0013_auto_20160618_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardprinting',
            name='rarity',
            field=models.CharField(choices=[('C', 'Common'), ('U', 'Uncommon'), ('R', 'Rare'), ('M', 'Mythic')], max_length=1),
        ),
    ]
