# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0014_auto_20160618_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=1, unique=True)),
                ('name', models.CharField(max_length=15, unique=True)),
                ('order', models.IntegerField(unique=True)),
            ],
        ),
    ]
