# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 04:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0016_auto_20160619_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardprinting',
            name='rarity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spellbook.Rarity'),
        ),
    ]
