# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0017_auto_20160619_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardprinting',
            name='flavour_text',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
