# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 13:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0018_auto_20160619_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercardchange',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 25, 13, 0, 38, 775068, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='cardprinting',
            unique_together=set([('set', 'card', 'collector_number', 'collector_letter')]),
        ),
        migrations.AlterUniqueTogether(
            name='cardprintinglanguage',
            unique_together=set([('language', 'card_name', 'card_printing')]),
        ),
        migrations.AlterUniqueTogether(
            name='userownedcard',
            unique_together=set([('card_printing_language', 'owner')]),
        ),
    ]
