# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 11:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0019_auto_20160625_2300'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subtype',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
