# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0020_auto_20160709_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='layout',
            field=models.CharField(default='normal', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cardprinting',
            name='collector_number',
            field=models.IntegerField(),
            preserve_default=False,
        ),
    ]
