# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0024_card_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardprintinglanguage',
            name='multiverse_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='card',
            name='layout',
            field=models.CharField(max_length=20),
        ),
    ]
