# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0025_auto_20160713_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardprintinglanguage',
            name='multiverse_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
