# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 06:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0027_auto_20160716_1625'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cardlink',
            unique_together=set([('card_from', 'card_to')]),
        ),
    ]
