# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 07:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0028_auto_20160716_1637'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cardruling',
            unique_together=set([('date', 'text', 'card')]),
        ),
    ]
