# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0029_auto_20160716_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardruling',
            name='text',
            field=models.CharField(max_length=4000),
        ),
    ]
