# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 12:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0032_auto_20160721_2254'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalCardLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_printing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spellbook.CardPrintingLanguage')),
                ('physical_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spellbook.PhysicalCard')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='cardlink',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='cardlink',
            name='card_from',
        ),
        migrations.RemoveField(
            model_name='cardlink',
            name='card_to',
        ),
        migrations.RemoveField(
            model_name='card',
            name='layout',
        ),
        migrations.RemoveField(
            model_name='usercardchange',
            name='card_printing_language',
        ),
        migrations.DeleteModel(
            name='CardLink',
        ),
        migrations.AddField(
            model_name='usercardchange',
            name='physical_card',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='spellbook.PhysicalCard'),
        ),
        migrations.AddField(
            model_name='userownedcard',
            name='physical_card',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='spellbook.PhysicalCard'),
        ),
        migrations.AlterUniqueTogether(
            name='userownedcard',
            unique_together=set([('physical_card', 'owner')]),
        ),
    ]
