# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 13:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0034_auto_20160723_2211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='physicalcardlink',
            old_name='card_printing',
            new_name='printed_language',
        ),
    ]
