# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 00:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0035_auto_20160723_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physicalcardlink',
            name='physical_card',
        ),
        migrations.RemoveField(
            model_name='physicalcardlink',
            name='printed_language',
        ),
        migrations.AddField(
            model_name='cardprintinglanguage',
            name='physical_card',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='spellbook.PhysicalCard'),
        ),
        migrations.DeleteModel(
            name='PhysicalCardLink',
        ),
    ]
