# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 06:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0036_auto_20160724_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardprintinglanguage',
            name='physical_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spellbook.PhysicalCard'),
        ),
        migrations.AlterField(
            model_name='userownedcard',
            name='physical_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spellbook.PhysicalCard'),
        ),
    ]
