# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 06:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0037_auto_20160724_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardprintinglanguage',
            name='card_printing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spellbook.CardPrinting'),
        ),
        migrations.AlterField(
            model_name='userownedcard',
            name='physical_card',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='spellbook.PhysicalCard'),
            preserve_default=False,
        ),
    ]
