# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 12:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0039_auto_20160724_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintingLanguagePhysicalLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physical_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spellbook.PhysicalCard')),
            ],
        ),
        migrations.RemoveField(
            model_name='cardprintinglanguage',
            name='physical_card',
        ),
        migrations.AddField(
            model_name='printinglanguagephysicallink',
            name='printing_language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spellbook.CardPrintingLanguage'),
        ),
        migrations.AlterUniqueTogether(
            name='printinglanguagephysicallink',
            unique_together=set([('printing_language', 'physical_card')]),
        ),
    ]
