# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 12:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0040_auto_20160726_2232'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrintingLanguagePhysicalLink',
            new_name='PhysicalCardLink',
        ),
    ]
