# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0041_auto_20160726_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mci_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='cardprinting',
            name='mci_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='set',
            name='mci_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
