# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 10:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0042_auto_20160731_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardprintinglanguage',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spellbook.Language'),
        ),
        migrations.AlterField(
            model_name='language',
            name='mci_code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
