# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0043_auto_20160731_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='mci_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
