# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 10:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0044_auto_20160731_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardFrom', to='spellbook.Card')),
                ('card_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardTo', to='spellbook.Card')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='cardlink',
            unique_together=set([('card_from', 'card_to')]),
        ),
    ]
