# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 10:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0045_auto_20160801_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardlink',
            name='card_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardFrom+', to='spellbook.Card'),
        ),
    ]
