# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0046_auto_20160801_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='mci_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
