# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-14 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0049_auto_20161106_1152'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='physicalcardlink',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='physicalcardlink',
            name='physical_card',
        ),
        migrations.RemoveField(
            model_name='physicalcardlink',
            name='printing_language',
        ),
        migrations.AddField(
            model_name='cardprintinglanguage',
            name='physical_cards',
            field=models.ManyToManyField(to='spellbook.PhysicalCard'),
        ),
        migrations.DeleteModel(
            name='PhysicalCardLink',
        ),
    ]
