# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-04 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0050_auto_20161114_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='cmc',
            field=models.FloatField(),
        ),
    ]
