# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-06 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0051_auto_20171204_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardprinting',
            name='flavour_text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
